### ISSUE TITLE
Extended experimental data

### ISSUE THREAD

**Issue by daccordeon** [daccordeon/gravexplain#10]
goals: improve amplitude and frequency limits

new kit to source from the labs:

- photo-diode/resistor for higher fps (faster response)
- horn/parabolic dish/reflector to amplify sound
- conversion for AC (red-black) to jack
- tin can and string
- suspension system (putty, water, strings) to make mirrors more sensitive

**Comment by daccordeon** [comment]
estimate noise level by adding in second signal
can only do once second speaker is sourced

**Comment by daccordeon** [comment]
spoke to my JayCar friend, and he said a whole bunch of useful things:
- LDR hysteresis is too much, basically webcam response time, (at least a ~10ms response time, which looks to kill any signals above 100Hz)

- photodiode would be great, just find one in the right wavelength range
i.e. https://au.rs-online.com/web/p/photodiodes/4975661/

- arduino vs raspberry pi is a consideration of cost vs usability
both have the capability to capture the time series we want, however:
- arduino, although cheaper, works at a slow capture rate without clever work to improve it (which is possible)
- data output to SD card is annoying, don't need to stream but would like to just save the datafile to desktop on USB connected PC or whatever 
- both have steep initial learning curves to implement, although the task we're interested in is sufficiently common for existing code to (hopefully) work
https://www.jaycar.com.au/arduino-learning
https://www.tinkercad.com/circuits

recommendation:
https://www.jaycar.com.au/duinotech-arduino-starter-kit/p/XC3902
https://www.jaycar.com.au/photodiode-5mm-led/p/ZD1948

https://au.rs-online.com/web/p/photodiodes/4975661/

**Comment by daccordeon** [comment]
raspberry pi benefits:
"""
This is because you'll get much better SD read/writes, it already has the card reading in-built, and you can also process the data as it's recorded in real time and plot that data which is much more useful for checking to make sure you're getting the data you think you are.
"""

**Comment by daccordeon** [comment]
https://electronics.stackexchange.com/questions/73732/how-to-use-sfh235-ir-photodiode-correctly

**Comment by hannahm8** [comment]
here's the specs for our laser:
https://www.thorlabs.com/thorproduct.cfm?partnumber=CPS532-C2

**Comment by daccordeon** [comment]
just as a note:
"""
The alternative is a phototransistor, which will give you an analogue signal out, but will require a more custom circuit to allow it to interface with the Arduino, unless you're able to find a purpose built module.

Just searching "arduino module ..." should likely exist somewhere already.
"""

**Comment by daccordeon** [comment]
also good to note: Blake has some custom code to direct capture live data from the arduino onto a USB connected PC, worth a try

**Comment by daccordeon** [comment]
things to do for week 3:
- add in microphone and second speaker, examine viterbi noise threshold (water noise in right band)
- attempt tin can to microphone capture
- set up Raspberry Pi (henceforth: R-Pi)
- when received, set up photo-diode circuit
- collect and process faster response data

**Comment by daccordeon** [comment]
audio commands for controlling internal mic:
https://askubuntu.com/questions/123798/how-to-hear-my-voice-in-speakers-with-a-mic?noredirect=1&lq=1

**Comment by daccordeon** [comment]
problems interfacing with surface: microphone not recognised, likely unless combined with USB port or re-combiner with speakers

**Comment by daccordeon** [comment]
for noise estimation, see pink noise for noise over the relevant band
https://mynoise.net/NoiseMachines/whiteNoiseGenerator.php

**Comment by daccordeon** [comment]
also, take spectrum of background room sound

**Comment by daccordeon** [comment]
raspberry pi set-up:
https://projects.raspberrypi.org/en/projects/raspberry-pi-setting-up/3
https://www.raspberrypi.org/downloads/noobs/
http://qdosmsq.dunbar-it.co.uk/blog/2013/06/noobs-for-raspberry-pi/

**Comment by daccordeon** [comment]
pi doesn't have analogue inputs, may need these so need an analogue-digital converter (ADC):
e.g. MCP3008
https://au.rs-online.com/web/p/general-purpose-adcs/7386651/
edit:acronym

**Comment by daccordeon** [comment]
better pins on this ADC:
https://au.rs-online.com/web/p/general-purpose-adcs/6696064/

**Comment by daccordeon** [comment]
result from end of week 3: photodiode works, appears to read light level but is very sensitive
week 4: begin measuring the interference pattern with the photodiode

**Comment by daccordeon** [comment]
if we can keep up a sampling rate of over 8kHz we should be able to capture all human speech
https://en.wikipedia.org/wiki/Voice_frequency
https://www.dpamicrophones.com/mic-university/facts-about-speech-intelligibility
current fps is at least 8kHz, so we look good for it
- - -
also look into audio play back from photodiode

**Comment by daccordeon** [comment]
correction: current fps is 16kHz, so we're well in the clear for observing the maximum frequency
- - - 
frequency resolution = fps / number of datapoints
however, the human voice is not a slowly changing continuous source, so viterbi tracking is not useful. even if we tried, the window width is small and so the number of datapoints decreases, leading to higher frequency uncertainty(resolution)
- - -
audio play-back after lunch

**Comment by daccordeon** [comment]
better quality audio through increasing intensity resolution:
- replicate 10-bit audio, or more realistically to current op amp -> 100 channel, by ripping audio from yt, pushing to 100 channels (in numpy), then play back in wav
- use this to determine if the kit has any chance of recognisable play back

**Comment by daccordeon** [comment]
looking at an impasse now having simulated the audio (which showed that digitisation should work).
tactical choice now is to reel back the project scope and write up the simple viterbi results.

**Comment by daccordeon** [comment]
try: threshold frequency noise

**Comment by daccordeon** [comment]
https://stackoverflow.com/a/19122540
F(f . g) = F(f) * F(g)

**Comment by daccordeon** [comment]
decided to keep this issue open until discussion is over on issue #11

**Comment by daccordeon** [comment]
actually, refreshing focus is good, this is moved to issue #11 from here
