### ISSUE TITLE
General comments 

### ISSUE THREAD

**Issue by hannahm8** [daccordeon/gravexplain#17]
General comments and to dos 

- [x] Convert footnotes to endnotes, blending them in with the bibliography. [E]
- [x] Also, use US English (color, not colour; defense, not defence, etc.). [E]

**Comment by hannahm8** [comment]
After reading and inspection of the manuscript I came to the conclusion that it is a research paper which should pass through critical discussion with researchers from gravitational wave community who should confirm that the audio signals produced in the way proposed in the manuscript, can indeed mimic real gravitational wave signals without confusion of students and teachers. Gravitational waves are transverse-traceless while the sound waves are purely longitudinal. In this respect there is no analogy between gravitational waves and audio signals whatsoever. [R1]
* From Hannah: I think we should point to other examples of where sound has been used as a GW analogy as part of our response here - the use of sound is not a new idea. It is true that GWs are not like sound waves, but the resulting data we get from an interferometer is very similar.
- [x] Draft response
- [x] Clarify references to other sound analogy work

**Comment by daccordeon** [comment]
I have passed the current work through an American English spell checker. (But we should do so again before submission)

**Comment by daccordeon** [comment]
The endnotes aren't showing up for me.

**Comment by hannahm8** [comment]
> The endnotes aren't showing up for me.

Hmm, okay - it could be how the PDF is compiled, what are you using? I'm using pdflatex and bibtex.

**Comment by daccordeon** [comment]
Scratch that, the endnotes work now. (For the record I am using pdflatex and bibtex but from inside LatexTools in Sublime Text)
