### ISSUE TITLE
Figures 

### ISSUE THREAD

**Issue by hannahm8** [daccordeon/gravexplain#19]
The axes label for frequency is not consistent across the figures: in some plots it is "f/Hz" and others "f(Hz)". [R3]
- [x] Make axis labelling consistent across figures

Figure 4: The three shades (or are there four?) indicating probability do not show up well in color, and worse, will be indistinguishable in black/white. I’m guessing that’s the reason I didn’t understand why certain paths were grey and not black. I'm guessing that's the reason I didn't understand why certain paths were grey and not black. [E]
- [x] Improve figure colouring
- [x] Improve clarity of Viterbi explanation [see also section IV comments] 

Fig. 5 is described as a heatmap. Please explain, in the caption, what the color coding indicates. Can you compare what is shown to what would be detected without using the VA? Is this “heatmap” the same representation as is often shown in LIGO publications? [E]
- [x] Add description of colour scale
- [x] Comparison to detection without Viterbi algorithm - think about how to do this
- [x] Comparison to LIGO paper plots

Fig. 6 is unnecessary; the differences from Fig. 1 are explained clearly in the text. [E]
- [x] Remove Fig. 6
- [x] Decide if part of it should be in Supplementary Material (perhaps the photo?)
 
Fig. 7: why is there a -100 dB difference in the signal level from 7a to 7b? [E]
- [x] Check and make sure this is correct or fix

Flow chart: Where in your flowchart are the various filters you describe? [E]
- [x] Add to caption

**Comment by daccordeon** [comment]
I've mentioned the heatmap's colouring. Not sure what [E] wants by a comparison to not using Viterbi, should it be compared to taking the Fourier transform of the whole data set and choosing the peak frequency (approximating the path as constant in time)?

**Comment by daccordeon** [comment]
Re: Removal of Figure 6
I've put the photo of the optical microphone in Supplementary Material along with the photo of the circuit in Appendix E.

**Comment by daccordeon** [comment]
Re: Flowchart
Added mention of filters to caption

**Comment by daccordeon** [comment]
Re: _Fig. 7: why is there a -100 dB difference in the signal level from 7a to 7b? [E]_
The Butterworth filter has strongly attenuated the signal outside the passband. (added to response)

**Comment by hannahm8** [comment]
@daccordeon, did you also shift the original source signal by 0.12s in the new versions of the results plots? (just want to check that what we have written in the caption is still correct)

**Comment by daccordeon** [comment]
> @daccordeon, did you also shift the original source signal by 0.12s in the new versions of the results plots? (just want to check that what we have written in the caption is still correct)

Yes, I did.

**Comment by hannahm8** [comment]
> I've mentioned the heatmap's colouring. Not sure what [E] wants by a comparison to not using Viterbi, should it be compared to taking the Fourier transform of the whole data set and choosing the peak frequency (approximating the path as constant in time)?

Good question, I'll think some more about what they are asking and see what Andrew thinks.


> > @daccordeon, did you also shift the original source signal by 0.12s in the new versions of the results plots? (just want to check that what we have written in the caption is still correct)
> 
> Yes, I did.

Perfect - thanks James :)

**Comment by hannahm8** [comment]
Changed schematic colour scheme to be more like our heatmap, worked through Viterbi section to improve clarity. 
James had made comparison plot to illustrate why we use Viterbi for wandering signals. 
Added details of comparing to LIGO heatmap plots in our referee response document.
