### ISSUE TITLE
Initial reading

### ISSUE THREAD

**Issue by daccordeon** [daccordeon/gravexplain#2]
- gravitational waves
- michelson interferometer
- - cone interference
- - collimator
- - webcam/human-eye frame-rate and limits of reading
- - frequency response of interferometer?
- continuous wave sources

**Comment by hannahm8** [comment]
Here are a few links related to continuous wave searches: 

This is a summary of a LIGO-Virgo paper where they search for continuous gravitational waves from Scorpius X-1. This was for "Observing Run 1", which ran in 2015-2016
<https://www.ligo.org/science/Publication-O1SidebandScoX1/index.php>
the search described was developed here and has recently been used on the "Observing Run 2" data as well, although there is no science summary for that yet as it is pretty new (that paper was led by a member of our group and here's the link for reference for later - but don't read it now: <https://arxiv.org/abs/1906.12040>). 

You can also see if there are other science summaries that are of interest to you here:
<https://www.ligo.org/science/outreach.php>

**Comment by daccordeon** [comment]
explanation of concentric circular fringes:
page 3 of
https://www.niser.ac.in/sps/sites/default/files/basic_page/Michelson%20Interferometer_P744%20-%20Optics.pdf

**Comment by daccordeon** [comment]
see reading_notes.txt

**Comment by hannahm8** [comment]
Here is a link for the photodiode I mentioned
<https://www.thorlabs.com/newgrouppage9.cfm?objectgroup_id=1285>

And here are a few links which could come in handy:

There's a bit more about continuous waves here: <https://astrobites.org/2018/01/29/hunting-for-gravitational-waves-from-spinning-neutron-stars/> (written by Lisa, who was a masters student with Andrew) and this overview which might be useful later on: <https://arxiv.org/abs/1712.05897>

To search for continuous gravitational waves, we use long stretches of data split up into many chunks, in the science summary, it mentions a hidden Markov model and talks about tracking the signal's frequency over time. One of the ways to find the path through frequencies efficiently is called the Viterbi Algorithm and there is an example of how that works here:
<https://www.youtube.com/watch?v=6JVqutwtzmo>

**Comment by daccordeon** [comment]
leaving this issue hanging until new reading issue is made

**Comment by daccordeon** [comment]
need resources for understanding matched filter and f-statistic

**Comment by daccordeon** [comment]
see issue #8 for new reading issue
