### ISSUE TITLE
Section V Complex Audio: Music and Speech

### ISSUE THREAD

**Issue by hannahm8** [daccordeon/gravexplain#20]
Overall big changes (common to several comments below)
- [x] Move material to Supplementary 
- [x] Rework section V 

Section V. What do you mean by an optical microphone device? “Cloth screen” over the photodiode? [E]
- [x] Add/clarify description of optical microphone device
- [x] Clarify why we use the cloth screen / what it is

Much of your description of the various filters should be moved to Supplementary Materials and/or referenced. This is a physics audience. More interesting is your observation that all filters degrade the signal in some way, i.e., they are all compromises.You could usefully expand that argument without becoming overly mathematical. [E]
- [x] Expand discussion of filter compromises

Sec VC: I feel that this section too long and is trying to fit too much of digital signal processing (DSP) in a limited space. The topic of digital filtering is not something that Physics undergraduates (or even graduates) are usually familiar with and requires a more gentle introduction than provided here. For example, the term "IIR" is introduced without explaining what the impulse response of a filter is (and there is no mention of FIR filters). Similarly, Eq. 4 **[now eq 2 in sup. mat]** looks like a Z-transform, and advanced topic in itself, but this is not mentioned and instead the term "complex frequency" is used that is likely to be unfamiliar to most readers. (Incidentally, there seems to be a notational inconsistency across the two sides of Eq.3: 'f' and 'omega'.) **now eq 1 in Sup. mat,.** To improve the readability of the paper, the authors should consider shortening this section by focussing on only the filtering procedure that worked the best. References to DSP textbooks may be provided for the interested reader to acquire background material.
- [x] Explain impulse response of filter [In Sup. Mat.]
- [x] Mention FIR fitlers [In Sup. Mat]
- [x] Do we need an explanation of Z-transform? [In Sup. Mat.]
- [x] Fix notation in Eq. 3 (f and omega) [now eq. 1 in Sup. Mat.]

**Comment by hannahm8** [comment]
While the authors have applied standard filtering methods in Sec. VC, the removal of high power line features from data in GW detectors is done using more sophisticated approaches. For example, cross- channel regression, linear predictive filtering, Kalman filtering etc. There are also some non-linear and non-parametric methods that have been explored in the GW literature. This point should be mentioned in the paper. [R3]

- [x]  Add discussion and references to GW noise subtraction in real detectors

**Comment by hannahm8** [comment]
This is not a comment but just my curiosity: How strong is the effect of mechanical vibrations of the camera or photodiode mount on the observed signal? [R3]
* From Hannah: do we have this information / differ to future study?

**Comment by daccordeon** [comment]
I've expanded the ideal filter versus compromises section.

**Comment by daccordeon** [comment]
re: _This is not a comment but just my curiosity: How strong is the effect of mechanical vibrations of the camera or photodiode mount on the observed signal? [R3]_

I have included a sentence about this in Future Work

**Comment by daccordeon** [comment]
We need Changrong for Section V~5 technical clarification

**Comment by hannahm8** [comment]
Changed H(\omega) -> H(f) for Butterworth filter (eq. 1 in Supplementary Material)

**Comment by hannahm8** [comment]
Have worked with Changrong to clarify supplementary material. Added discussion of noise mitigation in real detectors.
