### ISSUE TITLE
Section IV: Wandering Frequency Signal

### ISSUE THREAD

**Issue by hannahm8** [daccordeon/gravexplain#22]
The data analysis problems discussed in this paper are related to continuous wave searches. However, I did not find a mention of the key feature involved in these searches, namely, Doppler modulation of the signal frequency caused by the rotation of the Earth. This is the principal reason behind the extremely high computational cost of CW searches. A discussion of doppler modulation should be included. (It would be neat if the setup could be extended in the future to show the Doppler effect.)
- [ ] Clarify in discussion of detection statistics and mention Doppler modulation. 
- [ ] Check about computational cost (isn't it largely because we used months of data?)
- [x] Doppler effect study - mention in future work?

Is the HMM defined properly in Sec. IV A? The observables here are the amplitudes of the spectrogram pixels at a given time index and the hidden markov process is the underlying drift of frequency and amplitude of the signal. I was expecting to see a conditional pdf that connects the state of the underlying (suitably discretized) process to the observables. I don't see it. [R3]
- [ ] Check / fix this

Is Eq. 1 correct? The LHS is a marginal probability while the RHS is a joint probability. Shouldn't there be a marginalization on the RHS? [R3]
- [x] Check / fix

The normalization used for F(t_i, f_j) should be defined  explicitly. [R3]
- [x] Add definition

Looking at Fig. 3, it appears that the noise is not white and rises in power at lower frequencies. How is the color of the noise taken into account, if at all, in the HMM or the Viterbi algorithm? A discussion of this point should be included although it is fine to assume white noise as a first approximation. [R3]
- [x] Add discussion

The Viterbi algorithm used in this paper falls along the general lines of finding the optimal path through a chirplet graph (which
includes the spectrogram) that has been explored extensively in the GW literature. More broadly, the detection and estimation of chirp  signals, which leave a track in the time-frequency plane, has been a topic of many papers. For the benefit of the readers, the authors should provide an expanded literature review in Sec. IV A and state clearly if their approach is new and, if so, how it differs from the existing ones. A partial list of papers is given below: [R3]
E. Chassande-Mottin and A. Pai, Phys. Rev. D 73, 042003 (2006).
E. J. Candes, P. R. Charlton, and H. Helgason, Classical Quantum Gravity 25, 184020 (2008).
W. G. Anderson and R. Balasubramanian, Phys. Rev. D 60, 102001(1999).
P. Addesso, M. Longo, S. Marano, V. Matta, I. Pinto, and M.Principe, in 2015 3rd International Workshop on Compressed Sensing Theory and its Applications to Radar, Sonar and Remote Sensing (CoSeRa) (IEEE, New York, 2015), p. 154.
E. Thrane et al., Phys. Rev. D 83, 083004 (2011).
E. Thrane and M. Coughlin, Phys. Rev. D 89, 063012 (2014).
S. D. Mohanty, Phys. Rev. D D 96, 102008 (2017).
Margaret Millhouse, Neil J. Cornish, and Tyson Littenberg, Phys. Rev. D 97, 104057 (2018).
* From Hannah: I believe some of these are about searches for short duration signals, rather than CW's. I will check. 
- [x] Check papers
- [x] Add references
- [x] Clarify that Viterbi is not new, it follows many CW search papers

**Comment by hannahm8** [comment]
Section IV. The term “Markov process” may not be familiar to readers. [E]
- [x] Clarify / add explanation _[added sentence to define]_

While I applaud your efforts to explain the Viterbi algorithm (VA), I still think there’s room for improvement. I don’t understand how it improves the signal to noise ratio. [E]  [Also linked to Figure 4 comments in issue #19]
- [x] Clarify Viterbi algorithm explanation
- [x] Clarify that it's strength is in finding wandering signals

**Comment by daccordeon** [comment]
Re: _While I applaud your efforts to explain the Viterbi algorithm (VA), I still think there’s room for improvement. I don’t understand how it improves the signal to noise ratio. [E]_
I've added a paragraph to the end of Section IVa.

**Comment by daccordeon** [comment]
Mentioned Doppler effect in Future Work -- still needs mention earlier

**Comment by daccordeon** [comment]
Re: _Looking at Fig. 3, it appears that the noise is not white and rises in power at lower frequencies. How is the color of the noise taken into account, if at all, in the HMM or the Viterbi algorithm? A discussion of this point should be included although it is fine to assume white noise as a first approximation. [R3]_
I've added a discussion to the start of IVb

**Comment by hannahm8** [comment]
Corrected eqn 1, still need to: 
- [x]  Check consistency throughout section

**Comment by hannahm8** [comment]
- [x] mention prior being flat

**Comment by daccordeon** [comment]
Defined normalisation of detection statistic.

**Comment by daccordeon** [comment]
Added plot to aid in discussion about comparing VA to taking the spectrum of the entire timeseries.

**Comment by daccordeon** [comment]
Doppler mentioned in main text, HMM clarified with Andrew (by Hannah).
