### ISSUE TITLE
Andrew's comments on supplementary material

### ISSUE THREAD

**Issue by hannahm8** [daccordeon/gravexplain#25]
- [x] sec 1C - "Using a high... can be used..." - repetition, delete "Using"

- [x] fig 3 caption - "beyond -3 dB" - what does beyond mean in this context?

- [x] fig 4 caption - due to even stronger attenuation (and surrounding text) - this reads a bit unclear to me

- [x] after eq (2) - we say "In (2)" but neither w_0 nor B appear in (2)! Maybe replace In -> Derived from

- [x] footnote 1 - do you mean "element of real numbers" - if so should use proper real numbers symbol [or just omit, since it's obvious time is real]

**Comment by daccordeon** [comment]
All done in the [latest commit](https://github.com/daccordeon/gravexplain/commit/89bc2b56b565c9b3f1215a66df5a20b4d912553d).
