### ISSUE TITLE
Initial experimental data

### ISSUE THREAD

**Issue by daccordeon** [daccordeon/gravexplain#6]
- set-up and tune the interferometer
- capture 10s video and apply pipeline (i.e. track to get time-series then get fourier spectrum)
- add in piezo with low frequency AC source and repeat above

**Comment by daccordeon** [comment]
- capture longer video, bin into 10s chunks, apply pipeline
- apply viterbi to fourier frequency vs time

**Comment by daccordeon** [comment]
[expt_0.pdf](https://github.com/daccordeon/gravexplain/files/3937903/expt_0.pdf)

initial time series generated, tracker jumps in one ring, then back out

**Comment by daccordeon** [comment]
more videos taken and tracked
overall, tracking is very poor at high frequencies, and requires very slow and low amplitude oscillations
note: frequency resolution is fps/total_frames
[expt_1.pdf](https://github.com/daccordeon/gravexplain/files/3938045/expt_1.pdf)
[expt_2.pdf](https://github.com/daccordeon/gravexplain/files/3938044/expt_2.pdf)
[expt_3.pdf](https://github.com/daccordeon/gravexplain/files/3938043/expt_3.pdf)

---
still to do:
- add in piezo driven at low frequency
- apply viterbi to binned long capture

**Comment by daccordeon** [comment]
also:
- use external webcam to obtain better image

**Comment by hannahm8** [comment]
we could also try recording the intensity at the centre of the interference pattern to see if this can get high frequencies better than tracking

**Comment by daccordeon** [comment]
centre measurement provides similar results at low frequencies
at high frequencies is unclear if significantly better than tracker
note: likely that human driven high frequencies are very inconsistent, which might explain dips in signal and lack of signal in spectrum

[expt_0_centre.pdf](https://github.com/daccordeon/gravexplain/files/3942442/expt_0_centre.pdf)
[expt_3_centre.pdf](https://github.com/daccordeon/gravexplain/files/3942439/expt_3_centre.pdf)

---
going to the labs:
- external webcam to USB
- low voltage piezo with wires, e.g. PA1CEW or PA2JEW
- function generator

eventually:
- apply viterbi to binned long capture

edit: formatting and edit tag

**Comment by daccordeon** [comment]
adding in budget webcam and speaker driven by function generator produces very sharp results
note: expt_4_xxyy, driving frequency to speaker is xx.yy Hz

[expt_4_0209_centre.pdf](https://github.com/daccordeon/gravexplain/files/3943151/expt_4_0209_centre.pdf) 
[expt_4_0580_centre.pdf](https://github.com/daccordeon/gravexplain/files/3943150/expt_4_0580_centre.pdf)
[expt_4_2014_centre.pdf](https://github.com/daccordeon/gravexplain/files/3943149/expt_4_2014_centre.pdf)

---
first milestone by end of tomorrow:
- apply viterbi to binned long capture

edit: formatting

**Comment by daccordeon** [comment]
viterbi successful on long 5/10 minute captures
scanning_range, the amount that the viterbi path is allowed to change frequency in one long timestep is better left low at around 3-5 bins

[expt_ngrid_5_slow.pdf](https://github.com/daccordeon/gravexplain/files/3948343/expt_ngrid_5_slow.pdf)
[expt_viterbi_path_5_slow.pdf](https://github.com/daccordeon/gravexplain/files/3948342/expt_viterbi_path_5_slow.pdf)

---
all that's left for this issue:
- revise and document code
- convert to script

edit: formatting

**Comment by daccordeon** [comment]
also, although this is likely hard: 

- find point of lip of inner circle to measure instead of the video centre

**Comment by daccordeon** [comment]
see experiment_viterbi.py and .ipynb

closing this issue, open a new issue for further extensions
